export const LangStrings = {
    en: {
        Home_MainCall: "YOUR JOURNEY WILL NEVER BE THE SAME",
        Home_SecoundCall: "The best tools for your game you find here!",
        Home_Call: "Meet them now!",
        Home_Tolls: "KNOW OUR TOOLS",
        Home_TollsDescription: "The best tools for your game you",
        Home_TollsButtonPremium: "Discover the benefits of premium!",
        Home_RadarDefine: "Track, measure and plan.",
        Home_RadarObjetive:
            "This is the objective of SimaBosses, to mete and demonstrate in quickly and accurately the entire universe of Tibian bosses. In this tool, you find the most visual way, making your BossCheck even better.",
        Home_Find: "Here you will find:",
        Home_RadarChance: "Chance of appearance",
        Home_RadarGroupingLores: "Groupings by Lores",
        Home_RadarGroupingCities: "Groupings by Cities",
        Home_RadarPreview: "Appearance Schedule",
        Home_RadarButton: "Meet our boss session!",
        Home_CalcDefine: "Calculate, plan and execute..",
        Home_CalcObjetive:
            "SimaCalc came with the aim of making your Tibian life easier, bringing the greatest reliability and performance ever seen!",
        Home_CalcLoot: "Loot Division;",
        Home_CalcTraining: "Training Calculator",
        Home_CalcHunts: "Hunts Calculator",
        Home_CalcImbui: "Building Calculator",
        Home_CalcButton: "Meet our calculator",
        Home_LibraryDefine: "Data, data and more data..",
        Home_LibraryObjetive:
            "Easy for some, complex for others. With that in mind, we centralized the information in a single field, bringing all our conclusions and information in an environment in a unique and direct way.",
        Home_LibraryCall:
            "And a library is not just made of books.. Just imagine:",
        Home_LibraryArticles: "Articles and information",
        Home_LibraryInd: "Data and indicators",
        Home_LibraryHistory: "Stories, short stories and more",
        Home_LibraryLib: "Discover our library!",
        Home_WeAre: "Who we are?",
        Home_WeAreGuild: "SimaGuild or SimaEquipe?!",
        Home_WeAreDesc:
            "We arrived here not so alone, everything here was based on race and KS on the hunt!",
        Home_WeAreMeet: "Meet our team!",
        Home_Questions: "Are you in doubt?",
        Home_Questions2: "How does it work, what is DLD, when does it appear?!",
        Home_QuestionsDescribe:
            "Since the information is not few, we made an ideal guide for you to understand all the reports.",
        Home_QuestionsButton: "Know more",
        Modal_SelectServerTitle: "Select Server",
        Modal_SelectServerPlaceholder: "Select the desired server",
        Modal_SelectServerGo: "Go!",
    },
    pt: {
        Home_MainCall: "SUA JORNADA NUNCA MAIS SERÁ A MESMA",
        Home_SecoundCall:
            "As melhores ferramentas para o seu jogo você encontra aqui!",
        Home_Call: "Conheça-as agora!",
        Home_Tolls: "CONHEÇA NOSSAS FERRAMENTAS",
        Home_TollsDescription: "As melhores ferramentas para seu jogo",
        Home_RadarDefine: "Rastrear, mensurar e planejar..",
        Home_TollsButtonPremium: "Conheça os benefícios do premium!",
        Home_RadarObjetive:
            "Esse é o objetivo do SimaBosses, mepear e demonstrar de maneira rápida e precisa todo o universo dos bosses tibiano. Nesta ferramenta, você encontra a forma mais visual, deixando seu BossCheck cada vez melhor.",
        Home_Find: "Aqui você encontrará:",
        Home_RadarChance: "Chance de aparecimento",
        Home_RadarGroupingLores: "Agrupamentos por Lores",
        Home_RadarGroupingCities: "Agrupamentos por Cidade",
        Home_RadarPreview: "Agenda de Aparecimendo",
        Home_RadarButton: "Conheça nossa sessão de bosses!",
        Home_CalcDefine: "Calcular, planejar e executar..",
        Home_CalcObjetive:
            "A SimaCalc veio com o objetivo de facilitar a sua vida tibiana, trazendo a maior confiabilidade e desempenho já visto!",
        Home_CalcLoot: "Divisão de Loot",
        Home_CalcTraining: "Calculadora de Treino",
        Home_CalcHunts: "Calculadora de Hunts",
        Home_CalcImbui: "Calculadora de Imbuiements",
        Home_CalcButton: "Conheça nossa calculadora!",
        Home_LibraryDefine: "Dados, dados e mais dados..",
        Home_LibraryObjetive:
            "Fácil para alguns, complexo para outros.. Pensando nisso, centralizamos as informações em um só campo, trazendo todas as nossas conclusões e informações em um ambiente de forma única e diretamente.",
        Home_LibraryCall:
            "E uma biblioteca, não é só feita de livros.. Imagina só:",
        Home_LibraryArticles: "Artigos e informações",
        Home_LibraryInd: "Dados e indicadores",
        Home_LibraryHistory: "Histórias, contos e muito mais",
        Home_LibraryLib: "Conheça nossa biblioteca!",
        Home_WeAre: "Quem somos?",
        Home_WeAreGuild: "SimaGuild ou SimaEquipe?!",
        Home_WeAreDesc:
            "Chegamos aqui não tão só, tudo aqui foi na base da raça e do KS em hunt!",
        Home_WeAreMeet: "Conheça nossa equipe!",
        Home_Questions: "Tá com dúvida?",
        Home_Questions2: "Como funciona, o que é DLD, quando aparece?!",
        Home_QuestionsDescribe:
            "Já que as informações não são poucas, fizemos um guia ideal para você entender todos os relatórios.",
        Home_QuestionsButton: "Saiba mais",
        Modal_SelectServerTitle: "Selecionar Servidor:",
        Modal_SelectServerPlaceholder: "Selecione o Servidor Desejado",
        Modal_SelectServerGo: "Ir!",
    },
};

